version: "3.3"

networks:
  tinxy-net:

services:

  redis-sentinel:
    image: registry.mogify.com/agile-redis-sentinel
    volumes:
      - sentinel-conf:/etc/redis
    deploy:
      mode: global
    environment:
      - REDIS_MASTER_HOST=${REDIS_MASTER_IP}
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=15000
    networks:
      - tinxy-net
    ports:
      - target: 26379
        published: 16379
        mode: host

  redis-master:
    image: registry.mogify.com/agile-redis
    volumes:
      - redis-master-data:/data
      - redis-master-conf:/etc/redis
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == in-lb1
    networks:
      - tinxy-net

  redis-slave-node1:
    image: registry.mogify.com/agile-redis
    volumes:
      - redis-data:/data
      - redis-conf:/etc/redis
    environment:
      - REDIS_MASTER_HOST=${REDIS_MASTER_IP}
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == in-lb1
    networks:
      - tinxy-net

  redis-slave-node2:
    image: registry.mogify.com/agile-redis
    volumes:
      - redis-data:/data
      - redis-conf:/etc/redis
    environment:
      - REDIS_MASTER_HOST=${REDIS_MASTER_IP}
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == in2
    networks:
      - tinxy-net

volumes:
  redis-data:
  redis-conf:
  sentinel-conf:
  redis-master-data:
  redis-master-conf:
